name: Authenticate to Google Cloud
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        options: >-
          --health-cmd="curl --silent --fail http://localhost:7700/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          -p 7700:7700
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify config.yml exists
        run: ls -l $GITHUB_WORKSPACE/config.yml

      - uses: "google-github-actions/auth@v2.1.3"
        with:
          credentials_json: "${{ secrets.SECRETNILS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Set region for Cloud Run"
        run: "gcloud config set run/region us-central1"

      - name: "Run paymentapp"
        run: "gcloud run deploy paymenteapp --source . --allow-unauthenticated"

      - name: "Start Meilisearch with API Key"
        run: |
          docker run -d --name meilisearch -e MEILI_MASTER_KEY=${{ secrets.MEILISEARCH_API_KEY }} -p 7700:7700 getmeili/meilisearch:latest

      - name: "Start Meilisync"
        run: |
          docker run -d --name meilisync --mount type=bind,source=${GITHUB_WORKSPACE}/config.yml,target=/meilisync/config.yml long2ice/meilisync:latest

      - name: "Check Meilisync Logs"
        run: "docker logs meilisync"

      - name: "Check Meilisearch Logs"
        run: "docker logs meilisearch"

      - name: "Test Meilisearch Connection"
        run: |
          curl http://localhost:7700/health
          curl -X GET 'http://localhost:7700/indexes' -H 'Authorization: Bearer ${{ secrets.MEILISEARCH_API_KEY }}'
